[퍼블리싱]게시물_상세_댓글
dev-fath/chris-p-bacon pull request #39
Opened 2023-03-20 08:53 UTC by jsh612

## 1. 작업 내용
- 게시물 내 댓글 목록 퍼블리싱
<img width="564" alt="스크린샷 2023-03-20 오후 5 52 19" src="https://user-images.githubusercontent.com/48305402/226290599-9aa9bb6c-86ed-446e-9f5a-982763ab417e.png">

## 2. 리뷰 요청
- 

## 3. 관련 이슈
- clsoe #30 

## 4. 비고
-

2023-03-20 23:10 UTC, dev-fath requested changes

2023-03-20 23:10 UTC, dev-fath commented on src/components/reply/Replies.tsx
> +const Replies: React.FC<IRepliesProps> = ({ postId }) => {
```tsx 

const Replies = ({postId}: IRepliesProps) => {...}

```

이런식으로도 쓸 수 있습니다

알아두시면 좋습니다

2023-03-20 23:10 UTC, dev-fath commented on src/components/reply/Replies.tsx
> +                <div>{reply.text}</div>
글 내용 라인 수 제한 없든가요 ? 댓글 등록할 때 제한을 걸어줘야하는건가..

2023-03-20 23:10 UTC, dev-fath commented on src/pages/post/[id].tsx
> +        <div className="mt-sm h-[36px]  flex justify-between px-sm text-xs border-t-[1px] border-b-[1px] border-grayscale-500">
px단위 말고 rem단위 쓰면 좋을거같아요 

develop 풀 받고 h-4xl 하면 36px 나올거예요

2023-03-21 00:19 UTC, jsh612 commented on src/components/reply/Replies.tsx
> +                <div>{reply.text}</div>
@dev-fath 
댓글 글수 제한은 없는 것으로 보입니다.
필요하다면 저희가 임의로 제약 사항(입력 글자수 제한, 초기 표시 글자수 제한 + 더보기 버튼  등 ) 정해서 하는건 어떨까요??

추가적으로 댓글 관련 기능적인 사항은 #33 이슈에서  추가 작업하도록 하겠습니다.

2023-03-21 00:27 UTC, jsh612 commented on src/pages/post/[id].tsx
> +        <div className="mt-sm h-[36px]  flex justify-between px-sm text-xs border-t-[1px] border-b-[1px] border-grayscale-500">
@dev-fath 
해당 부분 수정 하였습니다.
[d18f9e1](https://github.com/dev-fath/chris-p-bacon/pull/39/commits/d18f9e1eb75044b3f6c196d360d19c9ac30a3944)

2023-03-21 05:32 UTC, dev-fath approved these changes

2023-03-21 05:38 UTC, merged